from .user import UserViewSet
from .curso import CursoViewSet
from .observacao import ObservacaoViewSet
from .nota import NotaViewSet
from .disciplina import DisciplinaViewSet
from .turma import TurmaViewSet
from .aluno import AlunoViewSet
from .trimestre import TrimestreViewSet
from .ocorrencia import OcorrenciaViewSet