# Generated by Django 5.1.2 on 2024-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_curso_remove_user_passage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
            ],
        ),
    ]
