# Generated by Django 5.1.2 on 2024-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_observacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observacao",
            options={"verbose_name": "Observação", "verbose_name_plural": "Observações"},
        ),
        migrations.AlterField(
            model_name="observacao",
            name="descricao",
            field=models.TextField(),
        ),
    ]
