# Generated by Django 5.1.2 on 2024-11-29 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="nota",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
