# Generated by Django 5.1.2 on 2024-11-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_nota_nota"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("nota", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.nota")),
            ],
        ),
    ]
