# Generated by Django 5.1.2 on 2024-11-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_disciplina"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="nota",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to="core.nota"),
        ),
    ]
