# Generated by Django 5.1.2 on 2024-11-29 14:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_disciplina_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disciplina",
            name="nota",
        ),
        migrations.AddField(
            model_name="nota",
            name="disciplina",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.disciplina"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "numeracao",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "ano",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.curso")),
            ],
        ),
    ]
