# Generated by Django 5.1.2 on 2024-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_disciplina_nota_nota_disciplina_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="abreviatura",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
