# Generated by Django 5.1.2 on 2024-11-29 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_turma_numeracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                (
                    "matricula",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="A matrícula deve conter exatamente 10 caracteres.", regex="^\\w{10}$"
                            )
                        ],
                    ),
                ),
                ("turma", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.turma")),
            ],
        ),
    ]
