# Generated by Django 5.1.2 on 2024-11-29 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_aluno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
