# Generated by Django 5.1.2 on 2024-11-29 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_aluno_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=100)),
                (
                    "ano",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(4),
                        ]
                    ),
                ),
            ],
        ),
    ]
