# Generated by Django 5.1.2 on 2024-11-29 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_trimestre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trimestre",
            name="ano",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(3000),
                ]
            ),
        ),
    ]
