# Generated by Django 5.1.2 on 2024-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_trimestre_ano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trimestre",
            name="descricao",
            field=models.CharField(max_length=10),
        ),
    ]
