# Generated by Django 5.1.2 on 2024-11-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_trimestre_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="aluno",
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to="core.aluno"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nota",
            name="trimestre",
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to="core.trimestre"),
            preserve_default=False,
        ),
    ]
