# Generated by Django 5.1.2 on 2024-11-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_nota_aluno_nota_trimestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="observacao",
            name="aluno",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.aluno"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="observacao",
            name="trimestre",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.trimestre"),
            preserve_default=False,
        ),
    ]
