# Generated by Django 5.1.2 on 2024-11-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_observacao_aluno_observacao_trimestre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.TextField()),
                ("aluno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.aluno")),
                ("trimestre", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.trimestre")),
            ],
        ),
    ]
