# Generated by Django 5.1.2 on 2024-11-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.responsavel"),
            preserve_default=False,
        ),
    ]
