# Generated by Django 5.1.2 on 2024-11-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_aluno_age_aluno_idade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="responsavel",
            options={"verbose_name": "Responsável", "verbose_name_plural": "Responsáveis"},
        ),
    ]
