# Generated by Django 5.1.2 on 2024-11-30 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_responsavel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="ocorrencias", to="core.aluno"
            ),
        ),
    ]
