# Generated by Django 5.1.2 on 2024-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_ocorrencia_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="observacao",
            name="acoes",
            field=models.CharField(
                choices=[
                    ("FAM", "Reunião Família Escola"),
                    ("GPE", "Participação em Grupo de Estudo"),
                    ("RSI", "Reunião SISAE"),
                    ("RCC", "Reunião Coordenação de Curso"),
                ],
                default=1,
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
