from .user import UserSerializer
from .curso import CursoSerializer
from .observacao import ObservacaoSerializer
from .nota import NotaSerializer
from .turma import TurmaSerializer
from .disciplina import DisciplinaSerializer
from .aluno import AlunoSerializer
from .trimestre import TrimestreSerializer
from .ocorrencia import OcorrenciaSerializer